source 'http://rubygems.org'

gem 'pry'
gem 'faker'
gem 'rspec'
gem 'bundler'
gem 'rubocop'
gem 'capybara'
gem 'httparty'
gem 'colorize'
gem 'site_prism'
gem 'documentos_br'
gem 'report_builder'
gem 'selenium-webdriver'